### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by buzdarbalooch** [kooscode/videotracker#1]
Hi,

i am trying to do something similar, it would be lovely, if you can provide some instructions. As i already have YOLO is doing detection task for my custom dataset. But i want to use (optical flow) to track certain objects.

**Comment by kooscode** [comment]
look at https://github.com/AlexeyAB/darknet  

he has a c++ wrapper that includes optical flow tracking helpers.  thats what i am using here.

you can also look at the main.cpp file in this repo, the code is fairly well documented.

**Comment by buzdarbalooch** [comment]
thanks alot for your help. Just another queston, do you know any other documentation from where we can have the understanding of the optical flow as a tracker. theoritical explanation i mean the way it is used with YOLO i mean .

**Comment by kooscode** [comment]
@buzdarbalooch, here is a good intro + a interactive JS implementation. https://docs.opencv.org/3.4/db/d7f/tutorial_js_lucas_kanade.html 

then refer to opencv docs and samples: https://docs.opencv.org/3.4/db/d7f/tutorial_js_lucas_kanade.html

in specific, here is the GPU Accellerated sample: https://github.com/opencv/opencv/blob/master/samples/gpu/pyrlk_optical_flow.cpp
